---
- name: install epel
  yum:
    name: epel-release
    state: present

- name: download barman
  get_url:
    url: https://dl.2ndquadrant.com/default/release/get/11/rpm
    dest: /tmp/barman-repo.sh
    mode: 0550

- name: install barman-repo
  shell: /tmp/barman-repo.sh
  args:
    creates: /etc/yum.repos.d/2ndquadrant-dl-default-release-pg11.repo

- name: install barman
  yum:
    name: 
      - barman
      - barman-cli
    state: present

- name: install pg-repo
  yum:
    name: https://download.postgresql.org/pub/repos/yum/reporpms/EL-7-x86_64/pgdg-redhat-repo-latest.noarch.rpm
    state: present

- name: install pg-server
  yum:
    name: postgresql11-server
    state: present

- name: init db
  shell: /usr/pgsql-11/bin/postgresql-11-setup initdb
  args:
    creates: /var/lib/pgsql/11/data/postgresql.conf

- name: create ssh dir
  file:
    path: "/var/lib/pgsql/.ssh"
    state: directory
    owner: postgres
    group: postgres

- name: copy ssh keys
  copy: src=files/ssh/{{ item }} dest=/var/lib/pgsql/.ssh/ mode=0600 owner=postgres group=postgres
  with_items:
    - id_rsa
    - id_rsa.pub
    - config

- name: copy pg config
  template:
    src: '{{ item }}'
    dest: /var/lib/pgsql/11/data
    mode: 0600
    owner: postgres
    group: postgres
  with_fileglob: files/*

- name: restart pg
  systemd:
    name: postgresql-11.service
    state: restarted

- name: create slot
  become_user: postgres
  shell: psql postgres -c "SELECT pg_create_physical_replication_slot('pg_slot_1')"

- name: create replica user
  become_user: postgres
  shell: psql postgres -c "CREATE USER replica WITH REPLICATION PASSWORD 'replica_pass'"

- name: create barman user
  become_user: postgres
  shell: psql postgres -c "CREATE USER barman WITH SUPERUSER PASSWORD 'barman_pass'"

- name: create barman_2 user
  become_user: postgres
  shell: psql postgres -c "CREATE USER barman_2 WITH REPLICATION PASSWORD 'barman_pass'"
