---
- hosts: all
  become: True
  roles:
    - add_hosts

- hosts: master
  become: True
  roles:
    - pg-master

- hosts: slave
  become: True
  roles:
    - pg-slave

- hosts: backup
  become: True
  roles:
    - barman